class Areas:
	CAVE = "Cave"
	CITY = "City"
	FOREST = "Forest"
	SWAMP = "Swamp"


class Enemies:
	BANDIT = "Bandit"
	BAYOU_BILL = "Bayou Bill"
	BAYOU_MAN = "Bayou Man"
	CAPTAIN_HOLE = "Captain Hole"
	DENNY_BILTMORE = "Denny Biltmore"
	DISGRACED_EXILE = "Disgraced Exile"
	GOON = "Goon"
	HAND_FISHERMAN = "Hand Fisherman"
	HIKER = "Hiker"
	HOBO = "Hobo"
	HUMANOID_CAVE_CREATURE = "Humanoid Cave Creature"
	HUNTER = "Hunter"
	MINER = "Miner"
	MOLE_PERSON = "Mole Person"
	PIMP = "Pimp"
	POACHER = "Poacher"
	SERIAL_KILLER = "Serial Killer"
	SKIN_COLLECTOR = "Skin Collector"
	SLEDGE_HAMMOND = "Sledge Hammond"
	SPELUNKER = "Spelunker"
	THE_MAYOR = "The Mayor"
	VOODOO_PRIESTESS = "Voodoo Priestess"


class Events:
	BOUNTY_COLLECTED = "bounty_collected"
	BUY_ITEM = "buy_item"
	BUY_PERK = "buy_perk"
	BUY_WEAPON = "buy_weapon"
	CRIT = "crit"
	DEPOSIT = "deposit"
	FLEE = "flee"
	HIT = "hit"
	KILL = "kill"
	LEVEL_UP = "level_up"
	MISS = "miss"
	SELL_ITEM = "sell_item"
	SELL_WEAPON = "sell_weapon"
	SWAP_WEAPON = "swap_weapon"
	TRAVEL = "travel"
	USE_ITEM = "use_item"
	WEAPON_BROKE = "weapon_broke"
	WITHDRAW = "withdraw"


class Items:
	BAG_OF_SLUDGE = "Bag of Sludge"
	CAMPBELLS_GOOP = "Campbell's Goop"
	CANNED_HORSE = "Canned Horse"
	CHICKEN_OF_THE_CAVE = "Chicken of the Cave"
	CRABS_ON_RYE = "Crabs on Rye"
	CRAY = "Cray"
	FROZEN_WAFFLE = "Frozen Waffle"
	GATOR_TESTICLES = "Gator Testicles"
	HOG_LOINS = "Hog Loins"
	KRILL = "Krill"
	MOONSHINE = "Moonshine"
	MOREL = "Morel"
	MUSKRAT_SKEWER = "Muskrat Skewer"
	MYSTERY_MEAT = "Mystery Meat"
	OCEAN_MAN_LUNCH_BOX = "Ocean Man Lunch Box"
	PROTEIN_GLOB = "Protein Glob"
	STALE_GREENS = "Stale Greens"
	SUSPICIOUS_GUMBO = "Suspicious Gumbo"
	TENCH_FILET = "Tench Filet"
	UNIDENTIFIED_MUSHROOMS = "Unidentified Mushrooms"


class Perks:
	AMBROSE_BLADE = "Ambrose Blade"
	BARTER_SAUCE = "Barter Sauce"
	BEER_GOGGLES = "Beer Goggles"
	BROWN_FRIDAY = "Brown Friday"
	BULLETPROOF = "Bulletproof"
	CROWS_NEST = "Crow's Nest"
	DEATH_CAN_WAIT = "Death Can Wait"
	DOCTOR_FISH = "Doctor Fish"
	GRAMBLIN_MAN = "Gramblin' Man"
	GRAMBLING_ADDICT = "Grambling Addict"
	HEALTH_NUT = "Health Nut"
	KARATE_LESSONS = "Karate Lessons"
	LEATHER_SKIN = "Leather Skin"
	LUCKY_TENCHS_FIN = "Lucky Tench's Fin"
	MARTIAL_ARTS_TRAINING = "Martial Arts Training"
	METAL_DETECTIVE = "Metal Detective"
	NEW_SNEAKERS = "New Sneakers"
	NOMADS_LAND = "Nomad's Land"
	RICKETY_PICKPOCKET = "Rickety Pickpocket"
	ROSETTI_THE_GYM_RAT = "Rosetti the Gym Rat"
	SLEDGE_FUND = "Sledge Fund"
	SOLOMON_TRAIN = "Solomon Train"
	TENCH_EYES = "Tench Eyes"
	TENCH_THE_BOUNTY_HUNTER = "Tench the Bounty Hunter"
	TRADE_SHIP = "Trade Ship"
	USED_SNEAKERS = "Used Sneakers"
	VAGABONDAGE = "Vagabondage"
	VAMPIRIC_SPERM = "Vampiric Sperm"
	WALLET_CHAIN = "Wallet Chain"
	WENCH_LOCATION = "Wench Location"


class Weapons:
	AXE = "Axe"
	BARE_HANDS = "Bare Hands"
	BAT = "Bat"
	BEAR_SPRAY = "Bear Spray"
	BRASS_KNUCKLES = "Brass Knuckles"
	BROKEN_BOTTLE = "Broken Bottle"
	CHAINSAW = "Chainsaw"
	CHILI_POWDER = "Chili Powder"
	CLAWS = "Claws"
	CROSSBOW = "Crossbow"
	CROWBAR = "Crowbar"
	FIRE_AXE = "Fire Axe"
	HARPOON = "Harpoon"
	HATCHET = "Hatchet"
	KNIFE = "Knife"
	MACHETE = "Machete"
	PEPPER_SPRAY = "Pepper Spray"
	PICKAXE = "Pickaxe"
	PISTOL = "Pistol"
	POCKET_SAND = "Pocket Sand"
	REVOLVER = "Revolver"
	RIFLE = "Rifle"
	SHOTGUN = "Shotgun"
	SHOVEL = "Shovel"
	SLEDGEHAMMER = "Sledgehammer"
	VOODOO_STAFF = "Voodoo Staff"


